// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvUNV1Lon47qcYe49Fs3akl0w7O8Lg1mk',
    appId: '1:502321345:web:b4ccaeff2a865415134440',
    messagingSenderId: '502321345',
    projectId: 'kstore-46682',
    authDomain: 'kstore-46682.firebaseapp.com',
    storageBucket: 'kstore-46682.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzKKhFJ8d39Q4V-sU0Wwn5vjjxeHJwSXQ',
    appId: '1:502321345:android:3aefd8a4a797b730134440',
    messagingSenderId: '502321345',
    projectId: 'kstore-46682',
    storageBucket: 'kstore-46682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeMs6VexQFRuRCyt8BrxVSOGRnE6opE1I',
    appId: '1:502321345:ios:7c0e8455c36fd56c134440',
    messagingSenderId: '502321345',
    projectId: 'kstore-46682',
    storageBucket: 'kstore-46682.appspot.com',
    androidClientId: '502321345-gaqevauollmbhkkb4od3ksgtioonl2n2.apps.googleusercontent.com',
    iosClientId: '502321345-j6r8ghnd4a78oi3j7045och2eo6rtsk5.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );
}
